name: WEBSLAMD
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.6.15=py310haa95532_0
  - libffi=3.4.2=hd77b12b_4
  - openssl=1.1.1q=h2bbff1b_0
  - pip=22.1.2=py310haa95532_0
  - python=3.10.4=hbb2ffb3_0
  - setuptools=63.4.1=py310haa95532_0
  - sqlite=3.39.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zlib=1.2.12=h8cc25b3_3
  - pip:
      - atomicwrites==1.4.1
      - attrs==22.1.0
      - cachelib==0.9.0
      - click==8.1.3
      - colorama==0.4.5
      - coverage==6.4.4
      - cycler==0.11.0
      - flask==2.1.2
      - flask-cors==3.0.10
      - flask-session==0.4.0
      - flask-wtf==1.0.1
      - fonttools==4.37.1
      - gunicorn==20.1.0
      - iniconfig==1.1.1
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.1.0
      - kiwisolver==1.4.4
      - lolopy==1.3.0
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - numpy==1.23.2
      - packaging==21.3
      - pandas==1.4.2
      - pillow==9.2.0
      - plotly==5.10.0
      - pluggy==1.0.0
      - py==1.11.0
      - py4j==0.10.9.7
      - pyparsing==3.0.9
      - pytest==7.1.1
      - pytest-cov==3.0.0
      - pytest-mock==3.8.1
      - python-dateutil==2.8.2
      - pytz==2022.2.1
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - seaborn==0.12.0
      - six==1.16.0
      - tenacity==8.0.1
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - werkzeug==2.2.2
      - wtforms==3.0.1
      - xlsxwriter==3.0.3
prefix: C:\Users\slueders\Anaconda3\envs\WEBSLAMD
