name: WEBSLAMD
channels:
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.10.4
  - setuptools=63.4.1
  - pip:
      - flask==2.1.2
      - flask-cors==3.0.10
      - flask-session==0.4.0
      - flask-wtf==1.0.1
      - gunicorn==20.1.0
      - jinja2==3.1.2
      - lolopy==1.3.0
      - numpy==1.23.2
      - pandas==1.4.2
      - plotly==5.10.0
      - pytest==7.1.1
      - pytest-cov==3.0.0
      - pytest-mock==3.8.1
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - wtforms==3.0.1
      - xlsxwriter==3.0.3